"""Public HTTP, RSS, and HTML-list ingestion adapters."""

from gribuki_trade.ingest.akshare_disclosures import (
    AKShareDisclosureConfig,
    AKShareDisclosureError,
    AKShareDisclosureSource,
    AKShareDisclosureTimeoutError,
)
from gribuki_trade.ingest.akshare_news import (
    AKShareNewsConfig,
    AKShareNewsError,
    AKShareNewsFeed,
    AKShareNewsSource,
    AKShareNewsTimeoutError,
)
from gribuki_trade.ingest.html import HtmlListConfig, HtmlListSource
from gribuki_trade.ingest.http import (
    HttpxNewsTransport,
    PublicHttpFetcher,
    SourceAccessDenied,
    SourceBackoffActive,
    SourceRateLimited,
    SourceUnavailable,
)
from gribuki_trade.ingest.official_macro import (
    CSRC_POLICY_INTERPRETATION_URL,
    CSRC_SOURCE_ID,
    FED_MONETARY_RSS_URL,
    FED_SOURCE_ID,
    NBS_DATA_RELEASE_URL,
    NBS_SOURCE_ID,
    PBOC_OPEN_MARKET_URL,
    PBOC_SOURCE_ID,
    PBOCOpenMarketSource,
    build_default_official_macro_sources,
    parse_pboc_open_market_list,
)
from gribuki_trade.ingest.rss import RssFeedSource
from gribuki_trade.ingest.search_discovery import (
    DEFAULT_OFFICIAL_DISCOVERY_HOSTS,
    DISCOVERY_CONFIRMED_EVENT_TYPE,
    DISCOVERY_HINT_EVENT_TYPE,
    TAVILY_SEARCH_ENDPOINT,
    DiscoveryCollection,
    DiscoveryConfirmationBasis,
    DiscoveryLineage,
    DiscoverySourcesExhausted,
    MultiProviderDiscoverySource,
    SearchAttemptFailure,
    SearchProviderAccessDenied,
    SearchProviderError,
    SearchProviderPayloadError,
    SearchProviderRateLimited,
    SearchProviderTimeout,
    SearchProviderTransportError,
    SearchProviderUnavailable,
    SearXNGSearchProvider,
    TavilySearchProvider,
    select_confirmed_discovery_events,
)

__all__ = [
    "AKShareDisclosureConfig",
    "AKShareDisclosureError",
    "AKShareDisclosureSource",
    "AKShareDisclosureTimeoutError",
    "AKShareNewsConfig",
    "AKShareNewsError",
    "AKShareNewsFeed",
    "AKShareNewsSource",
    "AKShareNewsTimeoutError",
    "HtmlListConfig",
    "HtmlListSource",
    "HttpxNewsTransport",
    "DEFAULT_OFFICIAL_DISCOVERY_HOSTS",
    "DISCOVERY_CONFIRMED_EVENT_TYPE",
    "DISCOVERY_HINT_EVENT_TYPE",
    "CSRC_POLICY_INTERPRETATION_URL",
    "CSRC_SOURCE_ID",
    "FED_MONETARY_RSS_URL",
    "FED_SOURCE_ID",
    "NBS_DATA_RELEASE_URL",
    "NBS_SOURCE_ID",
    "PBOC_OPEN_MARKET_URL",
    "PBOC_SOURCE_ID",
    "PBOCOpenMarketSource",
    "PublicHttpFetcher",
    "RssFeedSource",
    "DiscoveryCollection",
    "DiscoveryConfirmationBasis",
    "DiscoveryLineage",
    "DiscoverySourcesExhausted",
    "MultiProviderDiscoverySource",
    "SearchAttemptFailure",
    "SearchProviderAccessDenied",
    "SearchProviderError",
    "SearchProviderPayloadError",
    "SearchProviderRateLimited",
    "SearchProviderTimeout",
    "SearchProviderTransportError",
    "SearchProviderUnavailable",
    "SearXNGSearchProvider",
    "SourceAccessDenied",
    "SourceBackoffActive",
    "SourceRateLimited",
    "SourceUnavailable",
    "TAVILY_SEARCH_ENDPOINT",
    "TavilySearchProvider",
    "build_default_official_macro_sources",
    "parse_pboc_open_market_list",
    "select_confirmed_discovery_events",
]
