"""Deterministic feature and technical-signal engines."""

from .ashare_screening import (
    AShareFactorRanking,
    AShareScreeningConfig,
    HardFilterResult,
    RankedAShareCandidate,
    hard_filter_ashare_universe,
    rank_ashare_factor_cross_section,
)
from .ashare_surveillance import (
    AShareIntradayRanking,
    AShareIntradaySurveillanceConfig,
    IntradayAnomalyFactor,
    IntradayCandidate,
    IntradayCandidateClass,
    IntradayExclusionReason,
    IntradayFactorContribution,
    IntradayFactorSpec,
    rank_intraday_anomalies,
)
from .close_analysis import (
    CloseAnalysisConfig,
    CloseInstrumentType,
    CloseSignalFamilyStatus,
    CloseTechnicalAssessment,
    build_close_technical_assessment,
)
from .cross_market_relations import (
    MINIMUM_COMMON_SAMPLES,
    NON_CAUSALITY_NOTICE,
    AlignedFactorReturn,
    CrossMarketCorrelationSign,
    CrossMarketFactorRelation,
    CrossMarketFactorSeries,
    CrossMarketLagRelation,
    CrossMarketRelationFailureReason,
    CrossMarketRelationInputError,
    CrossMarketRelationsReport,
    CrossMarketRiskAlignment,
    CrossMarketRiskDirection,
    CrossMarketSignRegime,
    TargetCloseObservation,
    build_cross_market_relations,
)
from .technical import (
    TechnicalBar,
    TechnicalSignal,
    TechnicalSignalConfig,
    build_technical_signal,
)

__all__ = [
    "AShareFactorRanking",
    "AShareIntradayRanking",
    "AShareIntradaySurveillanceConfig",
    "AShareScreeningConfig",
    "MINIMUM_COMMON_SAMPLES",
    "NON_CAUSALITY_NOTICE",
    "AlignedFactorReturn",
    "CloseAnalysisConfig",
    "CloseInstrumentType",
    "CloseSignalFamilyStatus",
    "CloseTechnicalAssessment",
    "CrossMarketCorrelationSign",
    "CrossMarketFactorRelation",
    "CrossMarketFactorSeries",
    "CrossMarketLagRelation",
    "CrossMarketRelationFailureReason",
    "CrossMarketRelationInputError",
    "CrossMarketRelationsReport",
    "CrossMarketRiskAlignment",
    "CrossMarketRiskDirection",
    "CrossMarketSignRegime",
    "HardFilterResult",
    "IntradayAnomalyFactor",
    "IntradayCandidate",
    "IntradayCandidateClass",
    "IntradayExclusionReason",
    "IntradayFactorContribution",
    "IntradayFactorSpec",
    "RankedAShareCandidate",
    "TargetCloseObservation",
    "TechnicalBar",
    "TechnicalSignal",
    "TechnicalSignalConfig",
    "build_close_technical_assessment",
    "build_cross_market_relations",
    "build_technical_signal",
    "hard_filter_ashare_universe",
    "rank_ashare_factor_cross_section",
    "rank_intraday_anomalies",
]
