"""Backtest primitives shared by strategies and simulators."""

from gribuki_trade.backtest.costs import (
    InstrumentType,
    TradeCost,
    TradingCostConfig,
    calculate_trade_cost,
)
from gribuki_trade.backtest.crypto import (
    BacktestBarEvent,
    CryptoBacktestConfig,
    CryptoBacktestEngine,
    CryptoBacktestReport,
    CryptoBar,
    CryptoFeeConfig,
    CryptoOrderRequest,
    CryptoOrderType,
    CryptoStrategy,
    EquityPoint,
    InsufficientBalanceError,
    LiquidityRole,
    PortfolioSnapshot,
    SimulatedFill,
    SimulatedOrderResult,
    SimulatedOrderStatus,
    SpotLedger,
)
from gribuki_trade.backtest.recommendation_outcomes import (
    OutcomeStatus,
    OutcomeSummary,
    RecommendationEvaluationConfig,
    RecommendationOutcome,
    evaluate_recommendation,
    summarize_outcomes,
)

__all__ = [
    "BacktestBarEvent",
    "CryptoBacktestConfig",
    "CryptoBacktestEngine",
    "CryptoBacktestReport",
    "CryptoBar",
    "CryptoFeeConfig",
    "CryptoOrderRequest",
    "CryptoOrderType",
    "CryptoStrategy",
    "EquityPoint",
    "InsufficientBalanceError",
    "InstrumentType",
    "LiquidityRole",
    "OutcomeStatus",
    "OutcomeSummary",
    "RecommendationEvaluationConfig",
    "RecommendationOutcome",
    "PortfolioSnapshot",
    "SimulatedFill",
    "SimulatedOrderResult",
    "SimulatedOrderStatus",
    "SpotLedger",
    "TradeCost",
    "TradingCostConfig",
    "calculate_trade_cost",
    "evaluate_recommendation",
    "summarize_outcomes",
]
