"""清点根目录的 .tmp* 目录，并归档明确指定的证据。

本脚本绝不会删除来源目录。在 Windows 上，清理操作会通过已校验的
``Remove-Item -LiteralPath`` 调用单独执行，确保文件系统目标在破坏性操作
边界上始终清晰可见且可供复核。
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import stat
import tempfile
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

_SCHEMA_VERSION = 1
_REPRODUCIBLE_PURPOSE = "PYTEST_OR_REPRODUCIBLE_DIAGNOSTIC_OUTPUT"


@dataclass(frozen=True, slots=True)
class TreeInventory:
    name: str
    path: Path
    file_count: int
    size_bytes: int
    latest_mtime_utc: datetime
    tree_sha256: str
    files: tuple[dict[str, object], ...]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--workspace",
        default=str(Path(__file__).resolve().parents[1]),
    )
    parser.add_argument("--archive-root", default="runtime/archives")
    parser.add_argument(
        "--preserve",
        action="append",
        default=[],
        metavar="NAME=REASON",
        help="root .tmp directory and unique-evidence reason",
    )
    parser.add_argument("--label", default="root-temp-cleanup")
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--finalize-manifest")
    args = parser.parse_args()

    workspace = Path(args.workspace).expanduser().resolve()
    if args.finalize_manifest:
        return _finalize(Path(args.finalize_manifest).expanduser().resolve(), workspace)

    preserved = _preserved_reasons(args.preserve)
    inventories = tuple(
        _inventory(item)
        for item in sorted(workspace.iterdir(), key=lambda value: value.name)
        if item.name.startswith(".tmp") and item.is_dir()
    )
    names = {item.name for item in inventories}
    missing = sorted(set(preserved) - names)
    if missing:
        raise RuntimeError(f"preserved root temp directories are missing: {missing}")
    if not args.apply:
        print(
            json.dumps(
                {
                    "apply": False,
                    "directory_count": len(inventories),
                    "preserved": sorted(preserved),
                    "size_bytes": sum(item.size_bytes for item in inventories),
                    "workspace": str(workspace),
                },
                ensure_ascii=False,
                sort_keys=True,
            )
        )
        return 0

    archive_root = _absolute_from_workspace(workspace, args.archive_root)
    protected_authority = (workspace / "runtime/paper/day/2026-08-14").resolve()
    if _is_relative_to(archive_root, protected_authority) or _is_relative_to(
        protected_authority,
        archive_root,
    ):
        raise RuntimeError("archive root overlaps the protected PAPER-day authority")
    archive_root.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%S%fZ")
    archive = (archive_root / f"{args.label}-{timestamp}").resolve()
    if archive.exists():  # pragma: no cover - timestamp collision defense
        raise FileExistsError(archive)
    evidence_root = archive / "evidence"
    evidence_root.mkdir(parents=True)

    entries: list[dict[str, object]] = []
    for item in inventories:
        is_unique = item.name in preserved
        archived_relative: str | None = None
        retained_files: list[dict[str, object]] = []
        if is_unique:
            destination = evidence_root / item.name
            shutil.copytree(item.path, destination, copy_function=shutil.copy2)
            archived = _inventory(destination)
            if (
                archived.file_count != item.file_count
                or archived.size_bytes != item.size_bytes
                or archived.tree_sha256 != item.tree_sha256
            ):
                raise RuntimeError(f"archived evidence verification failed: {item.name}")
            archived_relative = destination.relative_to(archive).as_posix()
            retained_files = list(item.files)
        entries.append(
            {
                "archive_relative_path": archived_relative,
                "classification": (
                    "ARCHIVED_UNIQUE_EVIDENCE" if is_unique else _REPRODUCIBLE_PURPOSE
                ),
                "file_count": item.file_count,
                "files": retained_files,
                "latest_mtime_utc": item.latest_mtime_utc.isoformat(),
                "name": item.name,
                "reason": preserved.get(
                    item.name,
                    "Generated by pytest --basetemp or a reproducible diagnostic run.",
                ),
                "recoverability": (
                    "RECOVER_FROM_ARCHIVE_COPY"
                    if is_unique
                    else "REGENERATE_BY_RERUNNING_TESTS_OR_DIAGNOSTIC"
                ),
                "size_bytes": item.size_bytes,
                "source_path": str(item.path),
                "tree_sha256": item.tree_sha256,
            }
        )

    document: dict[str, object] = {
        "archive_created_at": datetime.now(UTC).isoformat(),
        "archive_path": str(archive),
        "authority_touched": False,
        "cleanup_applied": False,
        "cleanup_completed_at": None,
        "directory_count": len(entries),
        "entries": entries,
        "protected_authority_path": str(protected_authority),
        "schema_version": _SCHEMA_VERSION,
        "total_size_bytes": sum(item.size_bytes for item in inventories),
        "workspace": str(workspace),
    }
    _atomic_json(archive / "manifest.json", document)
    _atomic_text(archive / "manifest.md", _markdown(document))
    print(str((archive / "manifest.json").resolve()))
    return 0


def _finalize(manifest_path: Path, workspace: Path) -> int:
    document = json.loads(manifest_path.read_text(encoding="utf-8"))
    if not isinstance(document, dict) or document.get("schema_version") != _SCHEMA_VERSION:
        raise RuntimeError("unsupported temp-cleanup manifest")
    if Path(str(document.get("workspace"))).resolve() != workspace:
        raise RuntimeError("manifest workspace does not match --workspace")
    entries = document.get("entries")
    if not isinstance(entries, list):
        raise RuntimeError("manifest entries are invalid")
    remaining: list[str] = []
    for entry in entries:
        if not isinstance(entry, dict):
            raise RuntimeError("manifest entry is invalid")
        source = Path(str(entry.get("source_path"))).resolve()
        _require_root_temp(source, workspace)
        if source.exists():
            remaining.append(source.name)
        archived_relative = entry.get("archive_relative_path")
        if isinstance(archived_relative, str):
            archive_path = Path(str(document["archive_path"])).resolve()
            archived = _inventory((archive_path / archived_relative).resolve())
            if archived.tree_sha256 != entry.get("tree_sha256"):
                raise RuntimeError(f"archived evidence changed: {source.name}")
    if remaining:
        raise RuntimeError(f"root temp cleanup is incomplete: {remaining}")
    document["cleanup_applied"] = True
    document["cleanup_completed_at"] = datetime.now(UTC).isoformat()
    _atomic_json(manifest_path, document)
    _atomic_text(manifest_path.with_suffix(".md"), _markdown(document))
    print(str(manifest_path))
    return 0


def _inventory(path: Path) -> TreeInventory:
    resolved = path.resolve()
    _reject_reparse(resolved)
    rows: list[dict[str, object]] = []
    size = 0
    latest = datetime.fromtimestamp(resolved.stat().st_mtime, tz=UTC)
    for root, directories, filenames in os.walk(resolved, followlinks=False):
        root_path = Path(root)
        for name in directories:
            _reject_reparse(root_path / name)
        for name in filenames:
            file_path = root_path / name
            _reject_reparse(file_path)
            if not file_path.is_file():
                raise RuntimeError(f"unsupported non-file temp entry: {file_path}")
            file_stat = file_path.stat()
            digest = _file_sha256(file_path)
            relative = file_path.relative_to(resolved).as_posix()
            modified = datetime.fromtimestamp(file_stat.st_mtime, tz=UTC)
            latest = max(latest, modified)
            size += file_stat.st_size
            rows.append(
                {
                    "mtime_utc": modified.isoformat(),
                    "path": relative,
                    "sha256": digest,
                    "size_bytes": file_stat.st_size,
                }
            )
    rows.sort(key=lambda row: str(row["path"]))
    tree = hashlib.sha256()
    for row in rows:
        tree.update(str(row["path"]).encode("utf-8"))
        tree.update(b"\0")
        tree.update(str(row["size_bytes"]).encode("ascii"))
        tree.update(b"\0")
        tree.update(str(row["sha256"]).encode("ascii"))
        tree.update(b"\n")
    return TreeInventory(
        name=resolved.name,
        path=resolved,
        file_count=len(rows),
        size_bytes=size,
        latest_mtime_utc=latest,
        tree_sha256=tree.hexdigest(),
        files=tuple(rows),
    )


def _preserved_reasons(values: list[str]) -> dict[str, str]:
    result: dict[str, str] = {}
    for value in values:
        name, separator, reason = value.partition("=")
        if not separator or not reason.strip():
            raise ValueError("--preserve must use NAME=REASON")
        if not name.startswith(".tmp") or Path(name).name != name:
            raise ValueError("preserved name must be one root .tmp directory")
        if name in result:
            raise ValueError(f"duplicate preserved name: {name}")
        result[name] = reason.strip()
    return result


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while block := stream.read(1024 * 1024):
            digest.update(block)
    return digest.hexdigest()


def _reject_reparse(path: Path) -> None:
    value = path.stat(follow_symlinks=False)
    attributes = getattr(value, "st_file_attributes", 0)
    if path.is_symlink() or attributes & stat.FILE_ATTRIBUTE_REPARSE_POINT:
        raise RuntimeError(f"temp tree contains a reparse point: {path}")


def _require_root_temp(path: Path, workspace: Path) -> None:
    if path.parent != workspace or not path.name.startswith(".tmp"):
        raise RuntimeError(f"refusing non-root-temp path: {path}")


def _absolute_from_workspace(workspace: Path, value: str) -> Path:
    candidate = Path(value).expanduser()
    return (candidate if candidate.is_absolute() else workspace / candidate).resolve()


def _is_relative_to(candidate: Path, parent: Path) -> bool:
    try:
        candidate.relative_to(parent)
    except ValueError:
        return False
    return True


def _atomic_json(path: Path, value: object) -> None:
    rendered = json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n"
    _atomic_text(path, rendered)
    _atomic_text(
        path.with_name(f"{path.name}.sha256"),
        hashlib.sha256(rendered.encode("utf-8")).hexdigest() + "\n",
    )


def _atomic_text(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            prefix=f".{path.name}.",
            suffix=".tmp",
            dir=path.parent,
            delete=False,
        ) as stream:
            temporary = Path(stream.name)
            stream.write(value)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def _markdown(document: dict[str, object]) -> str:
    entries = document["entries"]
    assert isinstance(entries, list)
    rows = [
        "# Root temporary-directory cleanup manifest",
        "",
        f"- Archive: `{document['archive_path']}`",
        f"- Created: `{document['archive_created_at']}`",
        f"- Cleanup applied: `{str(document['cleanup_applied']).lower()}`",
        f"- Protected authority touched: `{str(document['authority_touched']).lower()}`",
        f"- Directories: `{document['directory_count']}`",
        f"- Total bytes: `{document['total_size_bytes']}`",
        "",
        "| Source | Classification | Files | Bytes | Latest UTC | Recoverability |",
        "|---|---:|---:|---:|---|---|",
    ]
    for entry in entries:
        assert isinstance(entry, dict)
        rows.append(
            "| "
            f"`{entry['name']}` | `{entry['classification']}` | "
            f"{entry['file_count']} | {entry['size_bytes']} | "
            f"`{entry['latest_mtime_utc']}` | `{entry['recoverability']}` |"
        )
    return "\n".join(rows) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
